on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        submodules: true
        lfs: true
    - name: Build using QPM and NDK
      uses: sc2ad/QuestNDKBuildAction@v0.1.1
      env:
       libname: clockmod
       github_token: ${{ secrets.GITHUB_TOKEN }}
       workspace: ${GITHUB_WORKSPACE}
