on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build using QPM and NDK
      uses: sc2ad/QuestNDKBuildAction@v0.1.1
      env:
       libname: clockmod
       github_token: ${{ secrets.GITHUB_TOKEN }}
       workspace: ${GITHUB_WORKSPACE}
