name: Pre-Release Mod

on:
  workflow_dispatch:

env:
     module_id: ClockMod
     prebuildnumber: 0

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        submodules: true
        lfs: true

    - uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Get the tag name
      run: echo "version=${GITHUB_REF/refs\/tags\//}-rc.${prebuildnumber}" >> $GITHUB_ENV

    - name: Get BSVersion and Version
      shell: pwsh
      run: |
        echo "BSVersion=$((Get-Content ./mod.template.json -Raw | ConvertFrom-Json).packageVersion)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        #echo "version=$((Get-Content ./qpm.shared.json -Raw | ConvertFrom-Json).config.info.version.Split('-')[0])-rc.$($env:prebuildnumber)"

    - name: Create ndkpath.txt
      run: |
        echo "$ANDROID_NDK_LATEST_HOME" > ${GITHUB_WORKSPACE}/ndkpath.txt

    - name: Get QPM
      if: steps.cache-qpm.outputs.cache-hit != 'true'
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: cargo-build.yml
        name: linux-qpm
        path: QPM
        repo: QuestPackageManager/QPM.CLI
        
    - name: QPM Collapse
      run: |
        chmod +x ./QPM/qpm
        ./QPM/qpm collapse
        
    - name: QPM Dependencies Cache
      id: cache-qpm-deps
      uses: actions/cache@v2
      env:
        cache-name: cache-qpm-deps
      with:
        path: /home/runner/.local/share/QPM-RS/cache
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('qpm.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-
          ${{ runner.os }}-${{ env.cache-name }}
      
    - name: QPM Set Version & Restore
      run: |
        ./QPM/qpm package edit --version ${{ env.version }}
        ./QPM/qpm restore

    - name: Check dependency Folders
      run: |
        echo "Checking extern includes"
        ls -lh ${GITHUB_WORKSPACE}/extern/includes
        echo ""
        echo "Checking libs"
        ls -lh ${GITHUB_WORKSPACE}/extern/libs
        echo ""
        echo "Checking QPM/cache Folder"
        ls -lh $HOME/.local/share/QPM-RS/cache
        echo ""

    - name: Build
      run: |
        cd ${GITHUB_WORKSPACE}
        pwsh -Command ./build.ps1 -actions

    - name: Get Library Name
      id: libname
      run: |
        cd ./build/
        pattern="lib${module_id}*.so"
        files=( $pattern )
        echo "NAME=${files[0]}" >> $GITHUB_OUTPUT

    - name: Package QMOD
      run: |
        cd ${GITHUB_WORKSPACE}
        ./QPM/qpm qmod zip -i ./build/ -i ./extern/libs/ ${module_id}_${version}.qmod

    - name: Pre-Release
      uses: softprops/action-gh-release@v1
      with:
          name: ${{ env.module_id }} ${{ env.version }} for Beat Saber ${{ env.BSVersion }}
          files: |
            ./${{ env.module_id }}_${{ env.version }}.qmod
          body_path: ./pre-rl-notes.md
          generate_release_notes: true
          prerelease: true
          draft: true